# Generated by Django 5.0.1 on 2024-02-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_pgcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGCourse',
        ),
    ]
