# Generated by Django 5.0.1 on 2024-02-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_delete_pgcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholar', to='courses.course')),
            ],
        ),
    ]
