# Generated by Django 5.0.1 on 2024-02-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_scholarship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='course',
            new_name='Scholar',
        ),
    ]
