# Generated by Django 5.0.1 on 2024-02-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_course_scholarship_scholar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScholarShip',
        ),
    ]
